### ISSUE TITLE
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Alecapra96** [vuer-ai/feature-splatting#3] opened 2024-08-09 16:07 UTC
```(nerfstudio) C:\nerfstudio\feature-splatting>ns-train feature-splatting --data data/nerfstudio/poster
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\misc.py:184: RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.
  warnings.warn(
[Taichi] version 1.7.1, llvm 15.0.1, commit 0f143b2f, win, python 3.8.19
C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\tyro\_fields.py:330: UserWarning: The field colmap_path is annotated with type <class 'pathlib.Path'>, but the default value sparse/0 has type <class 'str'>. We'll try to handle this gracefully, but it may cause unexpected behavior.
  warnings.warn(
[13:05:23] Using --data alias for --data.pipeline.datamanager.data                                          train.py:230
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=WindowsPath('outputs'),
    method_name='feature-splatting',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-08-09_130523',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=WindowsPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'nerfstudio.pipelines.base_pipeline.VanillaPipeline'>,
        datamanager=FeatureSplattingDataManagerConfig(
            _target=<class 'feature_splatting.feature_splatting_datamgr.FeatureSplattingDataManager'>,
            data=WindowsPath('data/nerfstudio/poster'),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=NerfstudioDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>,
                data=WindowsPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                eval_mode='fraction',
                train_split_fraction=0.9,
                eval_interval=8,
                depth_unit_scale_factor=0.001,
                mask_color=None,
                load_3D_points=True
            ),
            camera_res_scale_factor=1.0,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            cache_images='gpu',
            cache_images_type='uint8',
            max_thread_workers=None,
            train_cameras_sampling_strategy='random',
            train_cameras_sampling_seed=42,
            fps_reset_every=100,
            feature_type='SAMCLIP',
            enable_cache=True
        ),
        model=FeatureSplattingModelConfig(
            _target=<class 'feature_splatting.model.FeatureSplattingModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=4096,
            prompt=None,
            warmup_length=500,
            refine_every=100,
            resolution_schedule=3000,
            background_color='random',
            num_downscales=2,
            cull_alpha_thresh=0.1,
            cull_scale_thresh=0.5,
            continue_cull_post_densification=True,
            reset_alpha_every=30,
            densify_grad_thresh=0.0008,
            densify_size_thresh=0.01,
            n_split_samples=2,
            sh_degree_interval=1000,
            cull_screen_size=0.15,
            split_screen_size=0.05,
            stop_screen_size_at=4000,
            random_init=False,
            num_random=50000,
            random_scale=10.0,
            ssim_lambda=0.2,
            stop_split_at=15000,
            sh_degree=0,
            use_scale_regularization=False,
            max_gauss_ratio=10.0,
            output_depth_during_training=False,
            rasterize_mode='classic',
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='off',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            ),
            python_compute_sh=False,
            feat_loss_weight=0.001,
            feat_aux_loss_weight=0.1,
            feat_latent_dim=13,
            mlp_hidden_dim=64
        )
    ),
    optimizers={
        'means': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.00016,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=1.6e-06,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'features_dc': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0025,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'features_rest': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.000125,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'opacities': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.05,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'scales': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.005,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'distill_features': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0025,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.0005,
                warmup_steps=0,
                max_steps=10000,
                ramp='cosine'
            )
        },
        'feature_mlp': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'quats': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'camera_opt': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.0001,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=0,
                lr_final=5e-07,
                warmup_steps=1000,
                max_steps=30000,
                ramp='cosine'
            )
        }
    },
    vis='viewer',
    data=WindowsPath('data/nerfstudio/poster'),
    prompt=None,
    relative_model_dir=WindowsPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=2000,
    steps_per_eval_batch=0,
    steps_per_eval_image=100,
    steps_per_eval_all_images=1000,
    max_num_iterations=30000,
    mixed_precision=False,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={}
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           Saving config to: outputs\poster\feature-splatting\2024-08-09_130523\config.yml      experiment_config.py:136
           Saving checkpoints to: outputs\poster\feature-splatting\2024-08-09_130523\nerfstudio_models    trainer.py:137
           Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:484
Extracting SAMCLIP features for 226 images...
Using cache found in C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main
Traceback (most recent call last):
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 262, in entrypoint
    main(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 247, in main
    launch(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 99, in train_loop
    trainer.setup()
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 153, in setup
    self.pipeline = self.config.pipeline.setup(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 255, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\nerfstudio\configs\base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "C:\nerfstudio\feature-splatting\feature_splatting\feature_splatting_datamgr.py", line 52, in __init__
    self.feature_dict = self.extract_features()
  File "C:\nerfstudio\feature-splatting\feature_splatting\feature_splatting_datamgr.py", line 101, in extract_features
    feature_dict = extract_fn(image_fnames, extract_args)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\nerfstudio\feature-splatting\feature_splatting\feature_extractor.py", line 106, in batch_extract_feature
    mobilesamv2, ObjAwareModel, predictor = torch.hub.load("RogerQi/MobileSAMV2", args.mobilesamv2_encoder_name)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\hub.py", line 566, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\hub.py", line 592, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\torch\hub.py", line 106, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\hubconf.py", line 4, in <module>
    from mobilesamv2.promt_mobilesamv2 import ObjectAwareModel
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\__init__.py", line 7, in <module>
    from .build_sam import (
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\build_sam.py", line 14, in <module>
    from .efficientvit.models.efficientvit.backbone import EfficientViTLargeBackbone
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\models\efficientvit\__init__.py", line 5, in <module>
    from .backbone import *
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\models\efficientvit\backbone.py", line 8, in <module>
    from mobilesamv2.efficientvit.models.nn import (
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\models\nn\__init__.py", line 6, in <module>
    from .drop import *
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\models\nn\drop.py", line 9, in <module>
    from mobilesamv2.efficientvit.apps.trainer.run_config import Scheduler
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\apps\trainer\__init__.py", line 5, in <module>
    from .base import *
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\apps\trainer\base.py", line 12, in <module>
    from mobilesamv2.efficientvit.apps.trainer.run_config import RunConfig
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\apps\trainer\run_config.py", line 10, in <module>
    from mobilesamv2.efficientvit.apps.utils import CosineLRwithWarmup, build_optimizer
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\apps\utils\__init__.py", line 7, in <module>
    from .export import *
  File "C:\Users\local_account/.cache\torch\hub\RogerQi_MobileSAMV2_main\mobilesamv2\efficientvit\apps\utils\export.py", line 8, in <module>
    import onnx
  File "C:\Users\local_account\anaconda3\envs\nerfstudio\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.```



my pip list 
(nerfstudio) C:\nerfstudio\feature-splatting>pip list
WARNING: Ignoring invalid distribution - (c:\users\local_account\anaconda3\envs\nerfstudio\lib\site-packages)
WARNING: Ignoring invalid distribution -erfstudio (c:\users\local_account\anaconda3\envs\nerfstudio\lib\site-packages)
Package                   Version        Editable project location
------------------------- -------------- ---------------------------------------
absl-py                   2.1.0
accelerate                0.31.0
anyio                     4.4.0
appdirs                   1.4.4
archspec                  0.2.3
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
astunparse                1.6.3
async-lru                 2.0.4
attrs                     23.2.0
av                        12.2.0
awscli                    1.33.20
Babel                     2.15.0
backcall                  0.2.0
beautifulsoup4            4.12.3
bidict                    0.23.1
bleach                    6.1.0
blinker                   1.8.2
boltons                   23.0.0
botocore                  1.34.138
Brotli                    1.0.9
cachetools                5.3.3
certifi                   2024.6.2
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        2.0.4
click                     8.1.7
clip                      1.0
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.8.2
comet-ml                  3.43.2
comm                      0.2.2
conda                     24.5.0
conda-libmamba-solver     24.1.0
conda-package-handling    2.3.0
conda_package_streaming   0.10.0
ConfigArgParse            1.7
configobj                 5.0.8
contourpy                 1.1.1
cryptography              42.0.8
cycler                    0.12.1
dash                      2.17.1
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
debugpy                   1.8.2
decorator                 5.1.1
defusedxml                0.7.1
descartes                 1.1.0
diffusers                 0.29.2
dill                      0.3.8
distro                    1.9.0
docker-pycreds            0.4.0
docstring_parser          0.16
docutils                  0.16
dulwich                   0.22.1
einops                    0.8.0
embreex                   2.17.7.post4
eval_type_backport        0.2.0
everett                   3.1.0
exceptiongroup            1.2.1
executing                 2.0.1
fastjsonschema            2.20.0
feature_splatting         0.0.2          C:\nerfstudio\feature-splatting
filelock                  3.15.4
fire                      0.6.0
Flask                     3.0.3
flatbuffers               24.3.25
fonttools                 4.53.0
fpsample                  0.3.2
fqdn                      1.5.1
frozendict                2.4.2
fsspec                    2024.6.1
ftfy                      6.2.0
gdown                     5.2.0
gin-config                0.5.0
gitdb                     4.0.11
GitPython                 3.1.43
google-auth               2.31.0
google-auth-oauthlib      1.0.0
grpcio                    1.64.1
gsplat                    1.0.0
h11                       0.14.0
h5py                      3.11.0
hloc                      1.5            c:\nerfstudio\hierarchical-localization
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.23.4
humanfriendly             10.0
idna                      3.7
igs2gs                    0.1.0
imageio                   2.34.2
imageio-ffmpeg            0.5.1
importlib_metadata        8.0.0
importlib_resources       6.4.0
intel-openmp              2021.4.0
ipykernel                 6.29.5
ipython                   8.12.3
ipywidgets                8.1.3
isoduration               20.11.0
itsdangerous              2.2.0
jaxtyping                 0.2.19
jedi                      0.19.1
Jinja2                    3.1.4
jmespath                  1.0.1
joblib                    1.4.2
json5                     0.9.25
jsonpatch                 1.33
jsonpointer               2.1
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.1
jupyter_server_terminals  0.5.3
jupyterlab                4.2.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.2
jupyterlab_widgets        3.0.11
kiwisolver                1.4.5
kornia                    0.7.3
kornia_rs                 0.1.4
lazy_loader               0.4
libmambapy                1.5.8
lightglue                 0.0
lightning-utilities       0.11.3.post0
loguru                    0.7.2
lxml                      5.2.2
mapbox-earcut             1.0.1
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
maskclip_onnx             1.0
matplotlib                3.7.5
matplotlib-inline         0.1.7
mdurl                     0.1.2
mediapy                   1.2.2
menuinst                  2.1.1
mistune                   3.0.2
mkl                       2021.4.0
mobilesamv2               1.0
mpmath                    1.3.0
msgpack                   1.0.8
msgpack-numpy             0.4.8
msvc-runtime              14.34.31931
multimethod               1.10
multiprocess              0.70.16
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nerfacc                   0.5.2
nerfstudio                1.1.3
nest-asyncio              1.6.0
networkx                  3.1
ninja                     1.11.1.1
nodeenv                   1.9.1
notebook                  7.2.1
notebook_shim             0.2.4
numpy                     1.24.4
nuscenes-devkit           1.1.9
oauthlib                  3.2.2
onnx                      1.16.2
onnxruntime               1.18.1
onnxsim                   0.4.36
open3d                    0.18.0
opencv-contrib-python     4.10.0.84
opencv-python             4.8.0.76
opencv-python-headless    4.10.0.84
overrides                 7.7.0
packaging                 23.2
pandocfilters             1.5.1
parso                     0.8.4
pathos                    0.3.2
pickleshare               0.7.5
pillow                    10.4.0
pip                       24.2
pkgutil_resolve_name      1.3.10
platformdirs              3.10.0
plotly                    5.22.0
pluggy                    1.0.0
plyfile                   1.0.3
pox                       0.3.4
ppft                      1.7.6.8
prometheus_client         0.20.0
prompt_toolkit            3.0.47
protobuf                  3.20.3
psutil                    6.0.0
pure-eval                 0.2.2
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycocotools               2.0.7
pycollada                 0.8
pycolmap                  0.6.1
pycosat                   0.6.6
pycparser                 2.21
pyequilib                 0.5.8
Pygments                  2.18.0
pyliblzfse                0.4.1
pymeshlab                 2023.12.post1
pyngrok                   7.1.6
pyparsing                 3.1.2
pyquaternion              0.9.9
pyreadline3               3.4.1
PySocks                   1.7.1
python-box                6.1.0
python-dateutil           2.9.0.post0
python-engineio           4.9.1
python-json-logger        2.0.7
python-socketio           5.11.3
pytorch-msssim            1.0.0
pytz                      2024.1
PyWavelets                1.4.1
pywin32                   306
pywinpty                  2.0.13
PyYAML                    6.0.1
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
rawpy                     0.21.0
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.2
requests-oauthlib         2.0.0
requests-toolbelt         1.0.0
retrying                  1.3.4
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.18.1
rsa                       4.7.2
Rtree                     1.2.0
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
s3transfer                0.10.2
safetensors               0.4.3
scikit-image              0.21.0
scikit-learn              1.3.2
scipy                     1.10.1
segment_anything          1.0
semantic-version          2.10.0
Send2Trash                1.8.3
sentry-sdk                2.7.1
setproctitle              1.3.3
setuptools                72.1.0
shapely                   2.0.4
shtab                     1.7.1
simple-websocket          1.0.0
simplejson                3.19.2
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.5
splines                   0.3.0
stack-data                0.6.3
svg.path                  6.3
sympy                     1.12.1
tabulate                  0.9.0
taichi                    1.7.1
tbb                       2021.13.0
tenacity                  8.4.2
tensorboard               2.14.0
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
tensorpack                0.11
termcolor                 2.4.0
terminado                 0.18.1
threadpoolctl             3.5.0
tifffile                  2023.7.10
timm                      0.6.7
tinycss2                  1.3.0
tinycudann                1.7
tokenizers                0.19.1
toml                      0.10.2
tomli                     2.0.1
torch                     2.1.2+cu118
torch-fidelity            0.3.0
torchmetrics              1.4.0.post0
torchpack                 0.3.1
torchtyping               0.1.4
torchvision               0.16.2+cu118
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.42.3
trimesh                   4.4.1
typeguard                 4.3.0
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
tyro                      0.8.5
uri-template              1.3.0
urllib3                   1.26.19
vhacdx                    0.0.8.post1
viser                     0.1.27
wandb                     0.17.3
wcwidth                   0.2.13
webcolors                 24.6.0
webencodings              0.5.1
websocket-client          1.8.0
websockets                12.0
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
win-inet-pton             1.1.0
win32-setctime            1.1.0
wrapt                     1.16.0
wsproto                   1.2.0
wurlitzer                 3.1.1
xatlas                    0.0.9
xxhash                    3.4.1
yourdfpy                  0.0.56
zipnerf                   0.1.0
zipp                      3.19.2
zstandard                 0.22.0

**Comment by RogerQi** [comment] 2024-08-11 18:08
This looks like an error with the ONNX library installation. Unfortunately, I don't have a Windows machine at hand to reproduce this error.

One potential solution is to not import onnx when the export function is not called (which is the case since we are just using MobileSAMV2's python backend for inference). I pushed a commit [here](https://github.com/RogerQi/MobileSAMV2/commit/c14389708ec6ee5ca86958ac85367719e1f62736) that may fix this issue for you. Can you try to remove the cached MobileSAMV2 codebase from your torch.hub cache and try the installation process again in a fresh conda environment?

**Comment by RogerQi** [comment] 2024-08-16 16:14
Any updates on this? If I don't receive a response in the next few days, I will assume my commit above works and close the issue.

**Closed as completed** 2024-08-20 12:04 UTC
